services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    platform: linux/arm64
    networks:
      - media-network

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Madrid
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    platform: linux/arm64
    networks:
      - media-network

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Madrid
    ports:
      - 8191:8191
    restart: unless-stopped
    platform: linux/arm64
    networks:
      - media-network

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Madrid
    volumes:
      - ./radarr/config:/config
      - ./downloads:/downloads
      - ./downloads/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped
    platform: linux/arm64
    networks:
      - media-network

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Madrid
    volumes:
      - ./sonarr/config:/config
      - ./downloads:/downloads
      - ./downloads/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
    platform: linux/arm64
    networks:
      - media-network

  plex:
    image: linuxserver/plex:latest
    container_name: plex-server
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Madrid
      - VERSION=docker
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./downloads/movies:/movies
      - ./downloads/tv:/tv
    restart: unless-stopped
    platform: linux/arm64

networks:
  media-network:
    driver: bridge

